### PR TITLE
BIP-681-Update-DAO-Multisig-Signers-and-Backup-Signers

### PR DESCRIPTION
**Pull request by Zen-Maxi**
Replaces Trent with Gosuto on all non testnet multisigs. Also transfers 500 BAL to each of 6 designated signer payment addresses.

https://forum.balancer.fi/t/bip-xxx-update-dao-multisig-signers-and-backup-signers/5909

### CODE REVIEW

**Review by gosuto-inzasheru — APPROVED** [review]
- pays 500bal to selected signers as per forum post
- rotates signer trent to gosuto on all production chains plus on optimism and fantom

**Comment by gosuto-inzasheru** [comment]
maybe also if passed change https://github.com/balancer/docs/blob/main/docs/concepts/governance/multisig.md accordingly

**Comment by Tritium-VLK** [comment]
Please wait to run this BIP until all signers are added to bal_addresses and reports come back with no unknown addresses.

**Review by gosuto-inzasheru — APPROVED** [review]

**Comment by Tritium-VLK** [comment]
Let's wait to merge here until all signers are registered in bal_addresses

**Comment by gosuto-inzasheru** [comment]
https://github.com/BalancerMaxis/bal_addresses/pull/421

**Pull request merged**
