### PR TITLE
[BIP-667] Roles V2 Migration & New Treasury Permissions

### PR DESCRIPTION
**Pull request by gosuto-inzasheru**
uploading in order to run report

edit: https://forum.balancer.fi/t/bip-xxx-roles-v2-migration-new-treasury-permissions/5742

### CODE REVIEW

**Review by gosuto-inzasheru — COMMENTED** [review]
hmm the data type issue might be on our side; looks like we cant handle the nested tuples in this data struct from hell: `['scopeFunction(bytes32,address,bytes4,(uint8,uint8,uint8,bytes)[],uint8)']` 😝

that being said though, @JeronimoHoulin how come your commit to change the safe (843be40) now also includes scope function calls? shouldnt all perms already be included in the policy installed on the new module `0x13c61a25DB73e7a94a244bD2205aDba8b4a60F4a`?

also, what about the old roles module (`0xd8dd9164E765bEF903E429c9462E51F0Ea8514F9`)? are there plans to disable it?

**Comment by JeronimoHoulin** [comment]
Thanks for flagging the additional scope function calls @gosuto-inzasheru, they were additional features we wanted to implement in a near future, but given they are not written in the Zodiac Roles v2 [proposal](https://forum.balancer.fi/t/bip-xxx-roles-v2-migration-new-treasury-permissions/5742), we'll stick to only matching the correct Safe, and implement new features in future proposals.

With regards to the old roles module; with the execution of Roles v2 all necessary revokes are executed on Roles v1. Mentioned [here](https://forum.balancer.fi/t/bip-xxx-roles-v2-migration-new-treasury-permissions/5742).

**Comment by gosuto-inzasheru** [comment]
payload currently fails an internal integrity check in tenderly sim, requested clarification from the kpk team: https://dashboard.tenderly.co/public/safe/safe-apps/simulator/dafa3024-7970-481b-a773-c30eb0bf6fcb?trace=0.1.7.0.2.0.1.0

**Review by gosuto-inzasheru — COMMENTED** [review]
- activates rolesv2 module on balancer's kpk managed safe
- permissions on this module are similar if not the same as the ones on the v1 module. extended review of the diff between the exisiting and new permissions policy: https://forum.balancer.fi/t/bip-xxx-roles-v2-migration-new-treasury-permissions/5742/4?u=gosuto)
- also adds a cap of 2% on the cow swap orders it is able to sign
- also adds the ability to unsign some cow swap orders

note: my review of the cow swap additions is largely based on kpk's permissions diff page they referenced ([ref](https://roles.gnosisguild.org/eth:0x13c61a25DB73e7a94a244bD2205aDba8b4a60F4a/roles/MANAGER/diff/FrBx1C1A4GSbQNBrMXcw6F5y3u0P4ksKQEXxoj99A)). it is impossible for me at this time to verify if this diff actually corresponds to the payload proposed here

**Comment by gosuto-inzasheru** [comment]
@Tritium-VLK yes this is reviewed and ready to go! i just could not stamp myself since i initiated the pr.

note that it doesnt simulate properly here but in safe ui it does

my review notes here: https://github.com/BalancerMaxis/multisig-ops/pull/1154#pullrequestreview-2217512260 and on the forum

**Review by Tritium-VLK — APPROVED** [review]

**Pull request merged**
