### PR TITLE
Transfer 3750 $ARB to beefy for  wstETH/ETH incentives program.

### PR DESCRIPTION
**Pull request by Tritium-VLK**

### CODE REVIEW

**Comment by Tritium-VLK** [comment]
From Frondoto
```
Ser @tritium_vlk . Boost contract ready.

https://arbiscan.io/address/0x12f0520DAFd65e6468d4dD4F79dd15b6589cb76a

duration is set to 8 days, I'm aiming to launch tomorrow, so it ends next wednesday. You can send the ARB amount there, I will make the PR now so its visible on the app.
```

**Comment by Tritium-VLK** [comment]
https://app.onchainden.com/safes/arb1:0xeD2Bc4e72Ed7D61FA4812a6B0E3d16F8Ad8369a1/transactions/0x768e3cf2406b638d5ea21e5081d920dd3f522ac04e1a8d10f99fb3971d6bf3f0?nid=392390

**Comment by frondoto** [comment]
Confirming the destination address is correct. BeefyBoost contract for Gyroscope wstETH-​ETH Vault. Duration 8 days.

**Comment by Tritium-VLK** [comment]
Executed

**Review by gosuto-inzasheru — APPROVED** [review]
https://arbiscan.io/tx/0x48cd46648943ebe81786f0b8c88087b19f14b210079b4756a951b2135d39aa22

**Pull request merged**
