### PR TITLE
sweep lm after cowamm ops

### PR DESCRIPTION
**Pull request by gosuto-inzasheru**

### CODE REVIEW

**Comment by Tritium-VLK** [comment]
D2D TX: https://etherscan.io/tx/0x151c4f0898e83d4469c9cdd09bc9096b58f9fedbd7d88a9d79ebde1ac94c66a3
BIP-516: https://forum.balancer.fi/t/bip-516-exit-from-d2d-bal-pool/5459

BAL In: 4,117.684223633350429406
D2D In: 18,880.096771716010835564

**Comment by Tritium-VLK** [comment]
## Governance Recap
[BIP-666: CowAMM](https://forum.balancer.fi/t/bip-666-provide-balancer-dao-pol-to-cowamm-pools/5895)
Total Budget:
125,000 USDC
213675.21 BAL
118.26 WETH

[BIP-669: 80/20 POL](https://forum.balancer.fi/t/bip-669-provide-80bal-20weth-weth-pol-on-ethereum/5894)
Total Budget: 
21978 BAL
24.45 WETH

[BIP-516](D2D POL removal):
Returned:
BAL: 4,117.684223633350429406
D2D: 18,880.096771716010835564

**Comment by Tritium-VLK** [comment]
## Funds Used:
[USDC/WETH POL](https://etherscan.io/tx/0x0552e4d6f47f0212a7d2a21f64e28d5fb6d6873af63ce970300db4fd24144c76)

USDC: -101,777.554411
WETH: -39.414999999999999723
BPTs returned: 5,194.381554063539272643

[80/20 POL 1](https://etherscan.io/tx/0xc5637d9ae4055332ed913d585a7e4959f906b5d51f041ffe8f478b3abd5e95fe)
WETH: 3.7725
BAL: 20,000
BPTs returned: 6,993.316813664651193628

[80/20 POL 2](https://etherscan.io/tx/0x4f963ff4ca80a147d05f436c183828b5370bbc56e9e5843313e5d143a8d08296)
WETH: 18.861
BPT: 6,993.316813664651193628 [ x ]
 
[BAL/WETH POL 1](https://etherscan.io/tx/0xfd876dd9c0512df412f1b12d10398d3a67d5ad19c92ec46f5910b72aadb71b8c)
WETH: 5
BAL: 6,683.6528780246985925

[BAL/WETH POL 2 + Incentives split] (batch execed tx) (https://etherscan.io/tx/0xe1db6f1d46d9bac73308845404f9de15918c9d6e834c938a29b83b7952805f3f)
WETH: 71.916500101507784707
BAL: 99,110.000000000000002056
BPTs returned: 146,039.11966192013122676
BAL sent to omnichain safe to run remaining COW incentive program: 6,683.652878 + 91,159.248127 = 91842.901005

[BAL/WETH POL 3 return of funds](https://etherscan.io/tx/0x7c7691a28f9f599c2dfa39efe49351465a5981fa6084d3e04f63703ac0cbc638)
BAL sent to DAO multisig: 1,043.947122069901445248


bCOWbaleth: 156,039.119661920131226849


[First week BAL incentives from LM multisig](https://etherscan.io/tx/0xfd876dd9c0512df412f1b12d10398d3a67d5ad19c92ec46f5910b72aadb71b8c)

BAL: 8,994.708995 + 91842.901005 = 100837.61

**Comment by Xeonus** [comment]
This sweep is not yet correct and would send HH rebates to DAO multisig @gosuto-inzasheru

For USDC amounts, we should look at the effective CoWAMM seed amount and only sweep the delta from the incoming 125k USDC for that operation

**Comment by Xeonus** [comment]
Based on my take on accounting ([sheet](https://docs.google.com/spreadsheets/d/1MTTOWUgRYeePCXmCUraQmH0KuUMEq3K34-e_VkAsgRU/edit?gid=0#gid=0)) we should send back:
- 23222.45 USDC
- 7139.65 BAL
- 3.745001 WETH
- 18880.096 D2D

@Tritium-VLK @gosuto-inzasheru

**Comment by Tritium-VLK** [comment]
Fina sheelt thanks to @gosuto-inzasheru and @Xeonus https://docs.google.com/spreadsheets/d/1MTTOWUgRYeePCXmCUraQmH0KuUMEq3K34-e_VkAsgRU/edit?gid=0#gid=0

**Comment by Tritium-VLK** [comment]
We seem to have more D2D than we got back out of LP?

**Review by Tritium-VLK — APPROVED** [review]
LGTM. Thanks everyone for taking the time to reconsile.

**Pull request merged**
