### PR TITLE
April2024_TritsQ1_PlusBonuses

### PR DESCRIPTION
**Pull request by Zen-Maxi**
Based upon these two spread sheets https://docs.google.com/spreadsheets/d/1sT_rWMKUIVzYZGgDCVp-1teUa5v9jtiema2Oh63ZY64/edit#gid=966891874 and https://docs.google.com/spreadsheets/d/17w-xe-weKt1N-ZaOtUeP3rj_eMBXJf_M0-vAcKGBWnE/edit#gid=1858870660

Tritium was entitled to 1434.256 stkauraBAL at the end of Q1 plus his bonus of 60.72175 additional. This will only be locked for 10.5 months. Hence the 10.5 / 12 * 31536000 duration for his vester being 27594000

Lipman receives 121.4435 Locked for one year.

Zen Dragon took a slight bonus drop for trit to get his full pay only 1.6 stkaurabal difference. Total bonus of 59.06487 stkauraBAL. Locked for one year.

Vester contract addresses can be confirmed in this bal_addresses file https://github.com/BalancerMaxis/bal_addresses/blob/main/extras/arbitrum.json

### CODE REVIEW

**Comment by Tritium-VLK** [comment]
I owe you a beer for the 1.6 stkAuraBAL ser.

**Review by Tritium-VLK — DISMISSED** [review]

**Review by gosuto-inzasheru — CHANGES_REQUESTED** [review]
@Tritium-VLK what are you approving? json is empty

**Comment by Zen-Maxi** [comment]
Hey filled json back in, and added veBAL payments + formatting changes to keep payroll section cleaner on a quarterly basis.

**Review by gosuto-inzasheru — COMMENTED** [review]
should this not also include stkaurabal comp for april for trit, mike and kraken?

also note that the q1/bonus vesting tx currently fails due to too low balance on the msig

**Comment by Tritium-VLK** [comment]
I was approving the intention, which I thought was kind of what we agreed for non-DAO msig requests.  Need some artifact that is a PR/ticket that has context in it and is attached to the siggy request (in den, or in sigops, or whatnot), really at best in den where it is durable.

**Review by gosuto-inzasheru — APPROVED** [review]
- vebal tx was executed already: https://etherscan.io/tx/0xe9a4f978a79098184d712b42c52de39ff92a9d906755906908ee75194ff6d949
- stkaurabal tx was executed already: https://arbiscan.io/tx/0x1b7e173747775e43ddd90a278410c16b489a59315fc8d188bde32835ae82836c

approving for now, but still not sure why stkaurabal for april isnt included in this as well..

**Pull request merged**
