### PR TITLE
BIP-520-Funding-Ecosystem-Onsite-Q2-2024

### PR DESCRIPTION
**Pull request by Zen-Maxi**
Sends 46475.05 USDC to Opco Multisig from Dao Multisig.

Simulation: https://dashboard.tenderly.co/public/safe/safe-apps/simulator/c8804dae-661b-444f-a666-f096758451d0

### CODE REVIEW

**Review by gosuto-inzasheru — APPROVED** [review]
Screenshot 2023-12-21 at 11 18 51

**Comment by Tritium-VLK** [comment]
> Screenshot 2023-12-21 at 11 18 51

**Comment by Tritium-VLK** [comment]
@gosuto-inzasheru we could rename the foundation multisig to opco.

**Comment by gosuto-inzasheru** [comment]
@Tritium-VLK why did you close without merging?

**Comment by Tritium-VLK** [comment]
@gosuto-inzasheru good question.  Reopining it and moving for exec next week.

**Comment by Tritium-VLK** [comment]
Note that the check failed because the prettier action couldn't find the new MaxiOps directory in this commit on the repo before we added it.  It printed the report first so you can see it still worked.

**Pull request merged**
