### PR TITLE
BIP-570: Enable Avalanche Foundation Community Coins Gauge [Avalanche]

### PR DESCRIPTION
**Pull request by Xeonus**
- enable Avlanche foundatino community gauge with a 2% cap

### CODE REVIEW

**Comment by Xeonus** [comment]
Pool information doesn't seem to properly map in the report. Root gauge maps to correct child chain gauge which maps to correct LP token which maps to correct pool: 
Childchaingauge: https://snowscan.xyz/address/0x72dD9b41FEc59cf58140cAb9C92CEfC8F212354D#readContract
LP token: https://snowscan.xyz/address/0x0df1Be54B29aA9828Bea1De6A6DFE3d03EC63082#readContract
Pool: https://snowscan.xyz/address/0x0df1Be54B29aA9828Bea1De6A6DFE3d03EC63082#readContract#F17

**Comment by gosuto-inzasheru** [comment]
> Pool information doesn't seem to properly map in the report. Root gauge maps to correct child chain gauge which maps to correct LP token which maps to correct pool: Childchaingauge: https://snowscan.xyz/address/0x72dD9b41FEc59cf58140cAb9C92CEfC8F212354D#readContract LP token: https://snowscan.xyz/address/0x0df1Be54B29aA9828Bea1De6A6DFE3d03EC63082#readContract Pool: https://snowscan.xyz/address/0x0df1Be54B29aA9828Bea1De6A6DFE3d03EC63082#readContract#F17

how did you map the lp token to the child gauge? it isnt verified on snowtrace

**Comment by gosuto-inzasheru** [comment]
ah we can actually verify the pool addy in the constructor calldata of the gauge creation:
```
Function: create(address pool)
MethodID: 0x9ed93318
[0]:
0000000000000000000000000df1be54b29aa9828bea1de6a6dfe3d03ec63082
```
ref: https://snowtrace.io/tx/0x2fc85e3d62551d727a28daac8e7efd76eaaaa45607a091142ac8dcd5ac3cf3f2?chainId=43114

**Review by gosuto-inzasheru — DISMISSED** [review]

**Review by gosuto-inzasheru — APPROVED** [review]

**Comment by Tritium-VLK** [comment]
Think the goal was to add this to core pools as well on avax.  Note that right now the only thing getting core pools are stake avax gauges and everything on that chain has been supported by avalabs incentives.

It doesn't look like this was mentioned in governance.  How do we want to handle it.  @Xeonus @Zen-Maxi @gosuto-inzasheru thoughts?

**Comment by Xeonus** [comment]
This pool simply doesn't qualify in any way to be a core pool based on our core pool framework. Period!

**Comment by Tritium-VLK** [comment]
After some discussion, it doesn't seem like we can add this just in here.  Will need to be addressed in future governance/another PR.

**Pull request merged**
