### PR TITLE
[BIP-662] Enable Gauge for ShezETH/wstETH

### PR DESCRIPTION
**Pull request by Xeonus**
- enable shezETH:wstETH gauge on mainnet
- no rate provider for shezETH, not rebasing
- [Proposal](https://forum.balancer.fi/t/bip-662-enable-gauge-for-shezeth-wsteth-with-2-cap-ethereum/5872)

### CODE REVIEW

**Review by gosuto-inzasheru — CHANGES_REQUESTED** [review]
gauge is not capped as per forum prop

**Comment by Xeonus** [comment]
Likely copy pasta from their side. Will check

**Comment by Tritium-VLK** [comment]
@Xeonus need to either merge this or not today.

**Comment by Tritium-VLK** [comment]
Will not merge this today/maxis can load it when everything is clear.

**Comment by Xeonus** [comment]
@gosuto-inzasheru and @Tritium-VLK this is an uncapped gauge. Was a copy padta error on their end, see forums and snapshot specs for correct uncapped setting. All good and confirmed by @Zen-Maxi

**Review by Zen-Maxi — APPROVED** [review]
All good 100% cap for ETH LSTs not a problem.

**Comment by Tritium-VLK** [comment]
@gosuto-inzasheru think you need to approve for this to merge.

**Review by gosuto-inzasheru — APPROVED** [review]

**Pull request merged**
