### PR TITLE
Change owner of arbi injector to kyc safe

### PR DESCRIPTION
**Pull request by Tritium-VLK**

### CODE REVIEW

**Comment by Tritium-VLK** [comment]
https://app.onchainden.com/safes/arb1:0x9ff471F9f98F42E5151C7855fD1b5aa906b1AF7e/transactions/0x0f133a8456cd1d2ee6c7c041223726356a569ecb81a1bc8baff1ce3b4c20f000?nid=365023

https://app.onchainden.com/safes/arb1:0xb6BfF54589f269E248f99D5956f1fDD5b014D50e/transactions/0xfe900da305d6cf07c44c978c6744224b4f7c963d2c871ed326a81336eb7721a4

**Comment by Tritium-VLK** [comment]
@gosuto-inzasheru note arbi injector needs to stay with kyc safe, at least the v1 one.

**Comment by Xeonus** [comment]
@Tritium-VLK just to be fully clear: this was the old injector used previously. So we changed ownership in between and now have to change back?
I am asking because I see the old injections here: https://arbiscan.io/address/0xf23d8342881edecced51ea694ac21c2b68440929#tokentxns

**Comment by Tritium-VLK** [comment]
This has been executed. @Zen-Maxi @Xeonus mind stamping when you have a chance?

**Pull request merged**
