### PR TITLE
[BIP-509] Wire Up Batch Relayer V6

### PR DESCRIPTION
**Pull request by gosuto-inzasheru**
- https://forum.balancer.fi/t/rfc-wire-up-batch-relayer-v6/5358
- used [action-scripts/gen_add_permissions_payload.py](action-scripts/gen_add_permissions_payload.py) to generate payloads for all chains
- script configuration can be found in [BIPs/00proposed/BIP-XXX/2023-11-21.json](BIPs/00proposed/BIP-XXX/2023-11-21.json):
  - allow the new batch relayer to call the necessary functions on the vault (`exitPool`, `joinPool`, `batchSwap`, `manageUserBalance`, `setRelayerApproval`, `swap`)

### CODE REVIEW

**Review by Tritium-VLK — CHANGES_REQUESTED** [review]
Looks good.  Can you now move it to either 2023-W47 (this week if you do it in the morning) or 2023-W48(next week) and make sure all the links work out.  I think the only thing you need to change is the very bottom on.  Then can post the BIP-XXX text to the Forum in the general proposals section.

**Review by Tritium-VLK — CHANGES_REQUESTED** [review]
Also if it's easy can you break out the changes to the generator as a separate PR so we can discuss that outside the context of the perm change?  We can probably get that merged before this one, so you don't need to modify this PR for that.

**Comment by gosuto-inzasheru** [comment]
https://forum.balancer.fi/t/bip-xxx-wire-up-batch-relayer-v6/5358

**Comment by Xeonus** [comment]
@gosuto-inzasheru coud you please move the files to a more suitable spot like 00proposed? AFAIK batched is after running merge scripts each week. Thanks :)

**Comment by gosuto-inzasheru** [comment]
done :)

**Review by Tritium-VLK — APPROVED** [review]

**Pull request merged**
