### PR TITLE
[BIP-741] Grant V3 Permissions to Maxis and Emergency DAO Multisigs

### LINKED ISSUE #1499: give maxis msig basic permissions for vault v3
current (v2!) basic perms that maxis have that would be needed from the start:

- [ ] `setSwapFeePercentage`
- [ ] `startAmplificationParameterUpdate`
- [ ] `stopAmplificationParameterUpdate`

ref: https://docs.balancer.fi/reference/authorizer/mainnet.html

### LINKED ISSUE #1500: give emergency msig necessary perms on vault v3
current (v2!) relevant perms for emergency msig are:

- [ ] `ProtocolFeeCollector.denylistToken `
- [ ] `PoolFactory.disable`
- [ ] `Pool.disableRecoveryMode`
- [ ] `Pool.enableRecoveryMode`
- [ ] `Pool.pause`
- [ ] `Pool.unpause`

ref: https://docs.balancer.fi/reference/authorizer/mainnet.html

### PR DESCRIPTION
**Pull request by gosuto-inzasheru**
closes #1499
closes #1500 

bip draft: https://docs.google.com/document/d/17uaFz-osYWUQlCk7a0ZSZZXj3QIL-LnPPlnmz5AbdQc/

### CODE REVIEW

**Comment by gosuto-inzasheru** [comment]
waiting for deployment of `v3-stable-pool` to get actions ids for `startAmplificationParameterUpdate(uint256,uint256)` and `stopAmplificationParameterUpdate()`

**Comment by Xeonus** [comment]
@gosuto-inzasheru according to @jubeira we should also make sure to add functionality to disable new pool creation via factories as for v2
image
See PR: https://github.com/balancer/balancer-deployments/pull/131

For currently missing action IDs for stable pools, once this PR is merged we have everything: https://github.com/balancer/balancer-deployments/pull/130

**Review by Xeonus — DISMISSED** [review]
- upgrade of workflow OK
- bump to bal address dependencies OK
- Cross checked [mainnet](https://github.com/balancer/balancer-deployments/blob/master/action-ids/mainnet/action-ids.json) and [gnosis](https://github.com/balancer/balancer-deployments/blob/master/action-ids/gnosis/action-ids.json) chain action IDs and can confirm they all match
- Permissions match desired initial set for launch

**Review by Xeonus — APPROVED** [review]
all still good, bump from dependencies

**Pull request merged**
