### PR TITLE
[BIP-669] Provide 80BAL-20WETH:WETH POL on [Ethereum]

### PR DESCRIPTION
**Pull request by Xeonus**
- [Proposal](https://forum.balancer.fi/t/bip-669-provide-80bal-20weth-weth-pol-on-ethereum/5894)

### CODE REVIEW

**Review by gosuto-inzasheru — APPROVED** [review]
prop should read:

> WETH: $60k / $2454 = 24.45

**Comment by Xeonus** [comment]
@gosuto-inzasheru thx, prop is fixed

**Comment by Ashkandirini** [comment]
Awli

**Comment by Tritium-VLK** [comment]
BAL for the cow incentives program was moved from the LM safe to the omnichain safe on mainnet to not mix bags.

**Pull request merged**
