### PR TITLE
BIP-352: Funding Proposal for the Integrations Team (Three Rocks)

### PR DESCRIPTION
**Pull request by Xeonus**
- 352A: send 125961 USDC and 62230.58 BAL in the week of August 1st 2023 to 0x3B8910F378034FD6E103Df958863e5c684072693
- Tenderly Sim 352A: https://dashboard.tenderly.co/public/safe/safe-apps/simulator/cbf1f479-dae4-4e71-8a72-55d48eb886d7
- 352B: send 180211 USDC in the week of October 1st 2023 to 0x3B8910F378034FD6E103Df958863e5c684072693
- Tenderly Sim 352B: https://dashboard.tenderly.co/public/safe/safe-apps/simulator/7e2702b6-e0f1-40cd-b5b2-9c16287c89aa

### CODE REVIEW

**Comment by Tritium-VLK** [comment]
image
image


Amounts for this week add up.

+ 180k USDC in W39  Amount looks good

Multisig looks good

@Xeonus W39 TX would pay out the Monday or Tuesday after W39 ends, which is probably like the 4-6th of October.

DO these funds need to be in place October 1 or is there some float?

**Review by Tritium-VLK — CHANGES_REQUESTED** [review]
Answer question about if W39 is too late.

**Comment by Xeonus** [comment]
In theory, OpCo holds enough funds to pay. I designated the payment to the closest next snapshot week. We can potentially also move this tx one week before.

**Comment by Tritium-VLK** [comment]
Pinged Danko and let him know to reqwuest a change if this will create cashflow problems.

**Pull request merged**
