### PR TITLE
BIP-537: Repay BAL to contributors who leant it to buy GGP 

### PR DESCRIPTION
**Pull request by Tritium-VLK**
@Tritium-VLK @Zen-Maxi will both explain the payments.

### CODE REVIEW

**Comment by Tritium-VLK** [comment]
I control the wallet `0x9010E01806518EDBbc84C083c5ff4e04b6622AE0`.  This wallet was only used for this operation.  I sold 3000 BAL for USDC on Arbitrum, bridged to Avax, and then bought GGP over a few chunks to take advantage of current  downward price movements/well manage slippage. 

A complete overview can best be seen on debank here: https://debank.com/profile/0x9010e01806518edbbc84c083c5ff4e04b6622ae0/history

**Comment by Zen-Maxi** [comment]
I control `0x25B70c8050B7e327Ce62CfD80A0C60cCcf057Fa6 `swapped bpt straight to usdc https://etherscan.io/tx/0x8a73443d054deec3a772621b5c93d099f01801ef23b6bb0f751a64aad276c073 then bridged extra to be sure we’d hit our number  https://etherscan.io/tx/0x8cba896891287f746b1d9b5b040442796499635a75ad9f524191d9f7022d25e5 then swapped for Ggp https://snowtrace.io/tx/0x379ba4e40eb59227a9d8f41291643379dc11f8b8b19c34322d3e7270c1905e75?chainId=43114 then sent https://snowtrace.io/tx/0x4a73ec11d7035bf33459c57223a877fcb1097ec92cbd6ee48024819e5d4a8189?chainId=43114

Multiplier for 8020BPT to BAL at the time 1170 * 3.03 BAL / BPT at the time = 3545 BAL.

**Comment by Tritium-VLK** [comment]
https://etherscan.io/tx/0x4f335b4c754955e81926793481c3d57c2d657fed66320a60d637bae0ce831ac7

**Review by gosuto-inzasheru — COMMENTED** [review]
already got execd?? https://etherscan.io/tx/0x982e22290cfca720fe896b10c764a4de8cd88eb4501c019f740c39166244521c

**Comment by Tritium-VLK** [comment]
@gosuto-inzasheru sorry this was not a DAO multisig tx, just checking in the payload for the onward payments.

**Pull request merged**
