### PR TITLE
BIP-607-Update-FTM-Multisig-to-Claim-vested-BEETS

### PR DESCRIPTION
**Pull request by Zen-Maxi**
The DAO Multisig ftm: `0xFe2022da08d17ac8388F5bEFE4F71456255105A4` will call `addOwnerWithThreshold` on itself six times, with the `threshold` equal to `6` and the following new `owner` addresses:

`0x7c2eA10D3e5922ba3bBBafa39Dc0677353D2AF17`
`0xafFC70b81D54F229A5F50ec07e2c76D2AAAD07Ae`
`0xc4591c41e01a7a654B5427f39Bbd1dEe5bD45D1D`
`0x7019Be4E4eB74cA5F61224FeAf687d2b43998516`
`0x11761c7b08287d9489CD84C04DF6852F5C07107b`
`0xcf4fF1e03830D692F52EB094c52A5A6A2181Ab3F`

These can be confirmed via [bal_addresses](https://github.com/BalancerMaxis/bal_addresses/blob/4396ca6ee46272111bb6db65e5054af079e58dda/extras/signers.json#L2)

The DAO Multisig ftm: `0xFe2022da08d17ac8388F5bEFE4F71456255105A4` will then interact with the vesting contract `0x8D381EC09356C3F1805c54B2BB0867e8b417DC3a` calling `release` with the BEETS token address `0xF24Bcf4d1e507740041C9cFd2DddB29585aDCe1e` as the `token` argument.

Once the BEETS is received it will be bridged via Stargate to Optimism to the DAO Multisig on the Optimism network `0x043f9687842771b3dF8852c1E9801DCAeED3f6bc`

### CODE REVIEW

**Comment by gosuto-inzasheru** [comment]
https://forum.balancer.fi/t/bip-xxx-update-ftm-multisig-to-claim-vested-beets/5717

**Review by Tritium-VLK — APPROVED** [review]
@gosuto-inzasheru Looks good to me.  Are we sure if we batch these it will work, changing signers and then executing something onward. I've had odd problems with that before, but I imagine it should be fine in an atomic tx.

**Comment by gosuto-inzasheru** [comment]
all looks good in sim.

there are issues sometimes with switching multiple signers in a row (ie not atomically) because it checks the linked list of signers, and then detects a change. even though that is not the case here, that issue is actually mitigated by doing it atomically.

i dont see how this can particular tx can fail

**Review by Xeonus — DISMISSED** [review]

**Comment by Xeonus** [comment]
As discussed in the Maxi group, this BIP is not ready yet. Will go when ready. Until then do not merge yet. Will reassign / switch out other BIP with the currently assigned BIP number and replace this one once ready.

**Comment by gosuto-inzasheru** [comment]
current report runs are failing due to a bug, fix here: https://github.com/BalancerMaxis/bal_addresses/pull/306

i committed the report txts manually for now

**Review by gosuto-inzasheru — APPROVED** [review]
- adds the six maxis to the dao msig as a signer, threshold stays at 6
- claim beets from vesting contract and send it to the omnichain lm msig on ftm

**Review by Tritium-VLK — APPROVED** [review]

**Pull request merged**
