### PR TITLE
BIP-625: Enable gauge for WETH/rETH on [Gnosis]

### PR DESCRIPTION
**Pull request by Xeonus**
- enalbe rETH/WETH ECLP on Gnosis chain
- pending RP ready to merge: https://github.com/balancer/code-review/pull/76
- Proposal: https://forum.balancer.fi/t/bip-625-enable-gauge-for-weth-reth-on-gnosis/5797

### CODE REVIEW

**Comment by Xeonus** [comment]
@gosuto-inzasheru RP is under review, needs final approval coming in by EOW

**Comment by gosuto-inzasheru** [comment]
still waiting on rate provider peer review

**Comment by Xeonus** [comment]
Seems this RP is now [fully reviewed](https://github.com/balancer/code-review/blob/05ad8947a5c30cbb377a75abb7d0919b5ad0e038/rate-providers/registry.json#L1199)? Can we make sure this PR is included in execution next week @Tritium-VLK ? Thx

**Review by Tritium-VLK — APPROVED** [review]

**Comment by Tritium-VLK** [comment]
Rate provider review looks good.  W26 will run on Monday.

**Pull request merged**
