### PR TITLE
BIP-546: Enable weETH/ezETH/rswETH Gauge [Ethereum]

### PR DESCRIPTION
**Pull request by Xeonus**
- enable the LRT Tripool on mainnet ~~with a 10% cap~~

## Rate provider reviews
- weETH: https://github.com/balancer/code-review/blob/main/rate-providers/WeETH.md
- ezETH : https://github.com/balancer/code-review/blob/main/rate-providers/ezETHRateProvider.md
- rswETH: https://github.com/balancer/code-review/blob/main/rate-providers/rswethRateProvider.md

### CODE REVIEW

**Comment by Xeonus** [comment]
Proposal says 10% cap, payload run says uncapped - please verify @Zen-Maxi

**Comment by Xeonus** [comment]
Resolved - cap limit was incorrectly placed in the forum thread header. Uncapped gauge is correct

**Review by gosuto-inzasheru — APPROVED** [review]
- pool and gauge check out
- all rate providers have been reviewed as per the [registry](https://github.com/balancer/code-review/blob/main/rate-providers/registry.json)
- no cap

**Comment by gosuto-inzasheru** [comment]
please do note that the [forum post](https://forum.balancer.fi/t/bip-546-enable-weeth-ezeth-rsweth-gauge-ethereum/5569) and [snapshot](https://snapshot.org/#/balancer.eth/proposal/0xaa1f9eec0c26d3f50bdc370181836dc4101c15638fbbb5cdeb7727d229597873) text still mention a 10% gauge cap

**Pull request merged**
