### PR TITLE
[BIP-696] payload to unlock n' bridge GNO

### PR DESCRIPTION
**Pull request by JeronimoHoulin**
Tenderly simulation ran once again and looks great !
https://dashboard.tenderly.co/public/safe/safe-apps/simulator/4fdd317c-6dcd-43b5-bd5c-db8e3baf0e0e

Validation: 

```
ForeignOmnibridge
.
bridgeSpecificActionsOnTokenTransfer
(_token = 
0x6810e776880c02933d47db1b9fc05908e5386b96
,
_from = 
0x10a19e7ee7d7f8a52822f6817de8ea18204f2e4f
,
_receiver = 
0x0efccbb9e2c09ea29551879bd9da32362b32fc89
,
_value = 9051000000000000000000, _data = 0x)
=>
()
```

### CODE REVIEW

**Comment by gosuto-inzasheru** [comment]
prop: https://forum.balancer.fi/t/bip-xxx-transfer-gno-to-karpatkey-s-treasury-safe-authorise-staking-on-stakewise-v3/5954/

**Comment by gosuto-inzasheru** [comment]
from the [forum prop](https://forum.balancer.fi/t/bip-xxx-transfer-gno-to-karpatkey-s-treasury-safe-authorise-staking-on-stakewise-v3/5954#p-14557-abstract-1):
> 1. Grant permission to karpatkey to stake GNO on [Stakewise v3](https://x.com/stakewise_io/status/1816458408041574446).

i dont see this in this payload, did this already occur in the rolesv2 payload or is it still to be posted?

**Comment by gosuto-inzasheru** [comment]
@JeronimoHoulin can you add the other payload to this pr too please?

**Review by gosuto-inzasheru — DISMISSED** [review]
- withdraw locked gno
- bridge it to new kpk managed safe on gnosis
- remove kpk's eoa from said safe
- kpk managed safe on gnosis has rolesv2 mod configured to stake gno via multiple stakewise vaults

**Review by Zen-Maxi — APPROVED** [review]
For the sake of claiming and bridging the GNO this looks fully ok; will an additional BIP be executed or a Part 2 696 be proposed on this PR for claiming and staking later on?

**Comment by gosuto-inzasheru** [comment]
the staking permissions are included in the roles mod installed on the gnosis safe it is being bridge to, see my review [here](https://github.com/BalancerMaxis/multisig-ops/pull/1291#pullrequestreview-2312090466)

**Pull request merged**
