### PR TITLE
feat: support simple tuple argument

### LINKED ISSUE #1168: fix: bip report cannot handle arrayed tuple
eg `['scopeFunction(bytes32,address,bytes4,(uint8,uint8,uint8,bytes)[],uint8)']`, see https://github.com/BalancerMaxis/multisig-ops/pull/1154

### PR DESCRIPTION
**Pull request by gosuto-inzasheru**
closes #1168

### CODE REVIEW

**Comment by gosuto-inzasheru** [comment]
the simple tuple payload did not sim properly in tenderly before but does now:
- https://github.com/BalancerMaxis/multisig-ops/pull/1471

nested tuples is another issue for later:

**Review by Xeonus — CHANGES_REQUESTED** [review]
For clarification: is the simple_tuple usecase the standard one? Or do we need another "non-tuple" use-case to make sure simple payload reports don't break?

**Comment by gosuto-inzasheru** [comment]
@Xeonus "simple" as in non nested. for nested tuples i opened https://github.com/BalancerMaxis/multisig-ops/issues/1475

**Review by Xeonus — APPROVED** [review]
Test case coverage looks good. Works as intended for tuples

**Pull request merged**
