### PR TITLE
Additional logic to handle gyro rehype rate providers which are provided under different read functions.

### PR DESCRIPTION
**Pull request by Tritium-VLK**
See #853 for an example run, this branch was merged into that PR.

### CODE REVIEW

**Comment by gosuto-inzasheru** [comment]
am i missing something? https://github.com/BalancerMaxis/multisig-ops/pull/853#issuecomment-2027153375 still shows rate provider as empty

**Comment by gosuto-inzasheru** [comment]
it is because of the way you add the rate provider to the list:
```
>>> li = []
>>> li[0] = 'a'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: list assignment index out of range
```

should just use `.append` i think

**Comment by gosuto-inzasheru** [comment]
rate providers column is still empty.

suggesting to test this locally first and not here in prod

**Comment by Tritium-VLK** [comment]
In general I would really prefer complete reports on the final bathced payload, so kind of trying to move a little quick to get these dealt with during the 5 days we have (most of which is a long weekend).  That being siad you are right :)

**Comment by Tritium-VLK** [comment]
Ok @gosuto-inzasheru .  tested in dev env and in prod and looks good. agreed?

https://github.com/BalancerMaxis/multisig-ops/pull/853#issuecomment-2027195596

**Pull request merged**
