### PR TITLE
Fix:  report ci: Avoid scenitific numbers on human readable wei converstion

### PR DESCRIPTION
**Pull request by Tritium-VLK**
Solves #890

### CODE REVIEW

**Review by gosuto-inzasheru — CHANGES_REQUESTED** [review]
point of issue #890 is that now the amount is shown twice:

Screenshot 2024-04-16 at 14 12 18

the original wei (second list) should be removed imo

also i dont think casting to int is a smart idea here, what if there are actual decimals? eg usdc123,45?

**Comment by Tritium-VLK** [comment]
Good thoughts, how would you recommend casting these?  I kind of actually think it was ok that if it gets super large it goes to scientific notation.  Trying to figure out why the raw amount is duplicated.

**Comment by gosuto-inzasheru** [comment]
fix in cdabfe2

suggesting to use `Decimal` instead, this will prettify based on whether the decimal is significant or not and prevent floating precision loss

**Review by gosuto-inzasheru — APPROVED** [review]

**Comment by gosuto-inzasheru** [comment]
i cant request review from you @Tritium-VLK, but just merge as a review i guess :)

**Review by gosuto-inzasheru — APPROVED** [review]

**Comment by gosuto-inzasheru** [comment]
oh lol was on auto merge i think

**Pull request merged**
