### PR TITLE
[BIP-726] Adopt SEAL Whitehat Safe Harbor Agreement

### PR DESCRIPTION
**Pull request by DicksonWu654**
- Adopt SEAL Whitehat Safe Harbor Agreement on chain at `0x8f72fcf695523A6FC7DD97EafDd7A083c386b7b6`. Calling `adoptSafeHarbor` with the these parameters [balancerAdoptionParameters.json](https://github.com/user-attachments/files/17383766/balancerAdoptionParameters.json)

### CODE REVIEW

**Comment by Tritium-VLK** [comment]
@DicksonWu654 is there somewhere official to verify the contract at address `0x8f72fcf695523A6FC7DD97EafDd7A083c386b7b6`?  Perhaps some docs by Safe Harbor with deployment addresses?

**Comment by DicksonWu654** [comment]
Thank you for reviewing! 

Yep it's in the official github legal document here: https://github.com/security-alliance/safe-harbor/blob/main/documents/agreement.pdf

It's on page 9 or 1.1 c

Would you like it to be more explicit / more easily accessible?

**Comment by DicksonWu654** [comment]
Not sure why the tenderly simulation failed. I simulated it after I inputted the fields in the Gnosis Safe UI and it seemed to work: https://dashboard.tenderly.co/public/safe/safe-apps/simulator/dba0a8d3-cba7-4057-a583-be2320bb569a

**Comment by Tritium-VLK** [comment]
> Not sure why the tenderly simulation failed. I simulated it after I inputted the fields in the Gnosis Safe UI and it seemed to work: https://dashboard.tenderly.co/public/safe/safe-apps/simulator/dba0a8d3-cba7-4057-a583-be2320bb569a

The auto tenderly code doesn't always work on complex payloads.  Also the address decoding isn't working with all the special characters in the calldata.  We'll do a little work and see if we can improve things, but will of course check tenderly and addresses manually if we can't get our reporting to work.

**Comment by Tritium-VLK** [comment]
> Thank you for reviewing!
> 
> Yep it's in the official github legal document here: https://github.com/security-alliance/safe-harbor/blob/main/documents/agreement.pdf
> 
> It's on page 9 or 1.1 c
> 
> Would you like it to be more explicit / more easily accessible?

We add all known addresses to our [address book](https://github.com/BalancerMaxis/bal_addresses/tree/main/extras).  The PR to add involves a verification process.  At best there is somewhere I can link, and copypasta the same address from on an official safe harbor site.  I wasn't able to copy-paste the address easily in this PDF.  If it's not a hassle a slightly easier to handle reference would be nice :)

**Comment by DicksonWu654** [comment]
> > Not sure why the tenderly simulation failed. I simulated it after I inputted the fields in the Gnosis Safe UI and it seemed to work: https://dashboard.tenderly.co/public/safe/safe-apps/simulator/dba0a8d3-cba7-4057-a583-be2320bb569a
> 
> The auto tenderly code doesn't always work on complex payloads. Also the address decoding isn't working with all the special characters in the calldata. We'll do a little work and see if we can improve things, but will of course check tenderly and addresses manually if we can't get our reporting to work.

Ah let me try to do the payload without the \n :)

**Comment by DicksonWu654** [comment]
Alright just pushed something to remove all the extra spaces & remove the / from the "N/A". Not sure if that'll fix it though 😓

**Comment by DicksonWu654** [comment]
> > Thank you for reviewing!
> > Yep it's in the official github legal document here: https://github.com/security-alliance/safe-harbor/blob/main/documents/agreement.pdf
> > It's on page 9 or 1.1 c
> > Would you like it to be more explicit / more easily accessible?
> 
> We add all known addresses to our [address book](https://github.com/BalancerMaxis/bal_addresses/tree/main/extras). The PR to add involves a verification process. At best there is somewhere I can link, and copypasta the same address from on an official safe harbor site. I wasn't able to copy-paste the address easily in this PDF. If it's not a hassle a slightly easier to handle reference would be nice :)

Alrighty does this work? https://github.com/security-alliance/safe-harbor/blob/main/documents/deployment.txt

**Comment by 0xDanko** [comment]
Hey fellas, our in-house counselor had some bits to add on the agreement - I left a comment of the forum proposal. Also, please add that you will abide to the DAO standards and accountability guidelines.
[Balancer SAFE Harbor agreement (Balancer Edits)  (1).pdf](https://github.com/user-attachments/files/17415657/Balancer.SAFE.Harbor.agreement.Balancer.Edits.1.pdf)

**Comment by DicksonWu654** [comment]
> Hey fellas, our in-house counselor had some bits to add on the agreement - I left a comment of the forum proposal. Also, please add that you will abide to the DAO standards and accountability guidelines. [Balancer SAFE Harbor agreement (Balancer Edits) (1).pdf](https://github.com/user-attachments/files/17415657/Balancer.SAFE.Harbor.agreement.Balancer.Edits.1.pdf)

Hi! I replied on the forum!

**Comment by DicksonWu654** [comment]
Just updated the payload to reflect the new state. The changes are:

Identity Verification from `Anonymous` to `Named`
Diligence Requirement from "N/A" to "KYC & Global Sanction Verification. Balancer requires all eligible whitehats to undergo Know Your Customer (KYC) verification and be screened against global sanctions lists, including OFAC, UK, and EU regulations. This process ensures that all bounty recipients are compliant with legal and regulatory standards before qualifying for payment."

Simulated on tenderly here: https://dashboard.tenderly.co/public/safe/safe-apps/simulator/d21db244-0ead-4a1b-8803-fe5b5e768cc8/logs

Here are the parameters too [balancerAdoption.json](https://github.com/user-attachments/files/17428153/balancerAdoption.json)

**Review by gosuto-inzasheru — COMMENTED** [review]
current payload translates to:

- 10% bounty
- in $bal
- on chains ethereum, arbitrum, avalanche, base, fraxtal, gnosis, mode, optimism, polygon and zkevm
- requires kyc
- balancer vault as the account in question

balancer vault and dao msig addresses check out for all chains

**Comment by DicksonWu654** [comment]
Yes will do!

**Comment by gosuto-inzasheru** [comment]
@DicksonWu654 i just numbered this bip. if you can reflect that change in this pr we can approve it and include it in this week's gov round! sorry for all the admin, appreciate the efforts!

prop: https://forum.balancer.fi/t/bip-726-adopt-the-seal-safe-harbor-agreement/6087

**Comment by DicksonWu654** [comment]
> @DicksonWu654 i just numbered this bip. if you can reflect that change in this pr we can approve it and include it in this week's gov round! sorry for all the admin, appreciate the efforts!
> 
> prop: https://forum.balancer.fi/t/bip-726-adopt-the-seal-safe-harbor-agreement/6087

Thank you so much @gosuto-inzasheru! I just changed the BIP numbers!

**Review by gosuto-inzasheru — APPROVED** [review]

**Comment by gosuto-inzasheru** [comment]
@DicksonWu654 you payload executes this from our lm (liquidity mining) multisig, not the dao multisig. is this correct? (does it matter?)

**Comment by DicksonWu654** [comment]
> @DicksonWu654 you payload executes this from our lm (liquidity mining) multisig, not the dao multisig. is this correct? (does it matter?)

Oh no I didn't mean to do that 😓. Is it possible to change it, or would we need to re-do a DAO vote. But I think it's fine if it's from the lm multisig - as long as the DAO approved of it

**Pull request merged**
