### PR TITLE
Q3 karpatkey fees as per BIP-103  & BIP-648

### PR DESCRIPTION
**Pull request by JeronimoHoulin**
28,720 USDC in regards to [BIP-013 ](https://forum.balancer.fi/t/bip-103-karpatkey-balancer-treasury-cu-proposal-update/3895)

Calculations: https://docs.google.com/spreadsheets/d/1HT3FHsyFh6SQsNAPo-8QXn704VQKxaESR6ukNPgYWuk/edit?gid=462391640#gid=462391640

2,904.55 BAL in regards to [BIP-648](https://forum.balancer.fi/t/bip-648-balancer-dao-financial-reporting-by-karpatkey/5787) (i.e. "payments of 6,000 USD equivalent in BAL will be requested on a quarterly basis").

Calculations: https://docs.google.com/spreadsheets/d/1HT3FHsyFh6SQsNAPo-8QXn704VQKxaESR6ukNPgYWuk/edit?gid=187063405#gid=187063405

Tenderly simulation: https://dashboard.tenderly.co/public/safe/safe-apps/simulator/096b87af-8765-4c3e-9e25-2c2946323113

### CODE REVIEW

**Review by gosuto-inzasheru — COMMENTED** [review]
i cannot easily verify the data for the mgmt/perf fees, but if those are correct so is the payload. any way for us to confirm those data sources @JeronimoHoulin?

asking for final review from @0xDanko to make sure all this is in line with current legal agreements

**Review by gosuto-inzasheru — CHANGES_REQUESTED** [review]
ah also @JeronimoHoulin the folders correspond to the week the payloads gets executed in.

given the dao msig execs on a monthly basis, next execution oppo is week 44. can you adjust this?

**Comment by 0xDanko** [comment]
Thanks for pinging me, @gosuto-inzasheru 

BIP-013 performance fees are not covered by the Foundation's SLA, so should refer to the gov proposal itself.

As for BIP-648. I'd remark the BAL price is determined by the av. price during that quarter, which by my accounts (Coingecko) should be **1,8759462287937900**. This will also be on the gov proposal for reference. 
`"For the quarterly fees, the amount of BAL to be disbursed will be determined based on the 90-day moving average price of BAL on the last day of the third month of each quarter."`

**Comment by gosuto-inzasheru** [comment]
@JeronimoHoulin running the query in your gsheet for `WHERE date = DATE '2024-09-30'` returns `2.1493333333333493`

@0xDanko taking coingecko historical data (https://www.coingecko.com/en/coins/balancer/historical_data) and taking running average of the last 90 days yields `2.154847196` ([source](https://docs.google.com/spreadsheets/d/1FwlgYndViMXH0Qx4aW38TAWipyaAxVahqGtF8vHwqoc/edit?usp=sharing)).

suggesting to use the rounded average of both of `2.15`

the bal is then locked on their side afaiu:
> Furthermore, Karpatkey pledges to lock each payment in the veBAL contract for at least one year from the moment it is received in Karpatkey’s wallet.

**Comment by JeronimoHoulin** [comment]
Fixed BAL pricing (calculations: https://docs.google.com/spreadsheets/d/1HT3FHsyFh6SQsNAPo-8QXn704VQKxaESR6ukNPgYWuk/edit?gid=187063405#gid=187063405) and week nr as per Gosuto's request.
cc: @0xDanko @gosuto-inzasheru

**Review by Tritium-VLK — APPROVED** [review]

**Review by Tritium-VLK — APPROVED** [review]

**Review by gosuto-inzasheru — APPROVED** [review]

**Pull request merged**
