### PR TITLE
BIP-540: Enable rsETH gauges

### PR DESCRIPTION
**Pull request by Xeonus**
- enable rsETH/ETHx on mainnet
- enable rsETH/WETH on zkEVM
- Tenderly-sim: https://dashboard.tenderly.co/public/safe/safe-apps/simulator/c9829e62-67ef-4232-b255-1e1c260fbd97

### CODE REVIEW

**Comment by gosuto-inzasheru** [comment]
@Xeonus have both of those rseth rate providers been reviewed? i can only find the ethx one in the [threerock registry](https://github.com/threerocks-defi/code-review/blob/main/rate-providers/registry.json).

**Comment by gosuto-inzasheru** [comment]
ok looks like reviews were moved to https://github.com/balancer/code-review/

rseth has been reviewed here: https://github.com/balancer/code-review/blob/main/rate-providers/rsETHRateProvider.md

**Review by gosuto-inzasheru — COMMENTED** [review]
the rseth rate provider on zkevm is still under review: https://github.com/balancer/code-review/pull/10

rest looks good

**Comment by Xeonus** [comment]
@gosuto-inzasheru rate provider PR has been approved

**Pull request merged**
