### PR TITLE
Add BAL/WETH Gauge to zkevm Injector

### PR DESCRIPTION
**Pull request by Hyferion**
Polygon has agreed to add 12 weeks of 100 MATIC per week in incentives to the BAL/WETH pool.  @Hyferion coded it up to understand how the system works.

Note that there is a running program, so this replaces it.  **This payload should be executed by May 2 or not at all so that it properly overlaps with the currently running system. ** 

Add rewards transaction for gauge BAL/WETH 100 MATIC per week for 12 weeks
Fund 1200 injector with an additional 1200 matic. 

Current schedule: https://injector-schedule.web.app/zkevm/0x3fb4ee715987eD98EDbeEb144F9b6b034C4c9F02

Gyroscope ECLP wETH/rETH and Balancer rsETH/wETH StablePool still have 1 period remaining.

### CODE REVIEW

**Review by Tritium-VLK — APPROVED** [review]

**Comment by Tritium-VLK** [comment]
Let marketing know in case they want to mention it, plan to execute on Thursday the 1st of May.

**Comment by Tritium-VLK** [comment]
Stakable in UI: https://github.com/balancer/frontend-v2/pull/5625

**Comment by Tritium-VLK** [comment]
Loaded here: [NONCE 91](https://app.safe.global/transactions/tx?id=multisig_0xB59Ab49CA8d064E645Bf2c546d9FE6d1d4147a09_0xe17c4a46884ec4898d407c50462725fdd731242fb615ce1cb0f328d45c0fdb14&safe=zkevm:0xB59Ab49CA8d064E645Bf2c546d9FE6d1d4147a09)

**Review by gosuto-inzasheru — APPROVED** [review]

**Comment by gosuto-inzasheru** [comment]
> Loaded here: [NONCE 51](https://app.safe.global/transactions/tx?id=multisig_0xB59Ab49CA8d064E645Bf2c546d9FE6d1d4147a09_0xe17c4a46884ec4898d407c50462725fdd731242fb615ce1cb0f328d45c0fdb14&safe=zkevm:0xB59Ab49CA8d064E645Bf2c546d9FE6d1d4147a09)

i rejected this one due to it trying to send 1200eth instead of matic

**Review by Tritium-VLK — APPROVED** [review]

**Comment by Tritium-VLK** [comment]
Loaded the replaced Payload that won't revert and sends MATIC instead of ETH as Nonce 52. 

Please Reject Nonce 51, sign/exec Nonce 52.  Needs to be done today, or we need to regenerate the payload as 1 round will fire on the inecjtor.

**Comment by Tritium-VLK** [comment]
executed and staked a little something in the gauge to make the yields show up. @Hyferion you can check out the state of zkevm and look at the injector again now to see it all work.

**Pull request merged**
