### PR TITLE
New Chain Template -Maxi Safe - Provision on 3 new chains

### PR DESCRIPTION
**Pull request by Tritium-VLK**
Please sign/exec all 3 before mergting this PR

- [x] [Linea](https://safe.linea.build/transactions/tx?id=multisig_0x9ff471F9f98F42E5151C7855fD1b5aa906b1AF7e_0xb46462de93a2d0739f8c2a777896b4c85c6dd3de60502a5b4f9eadf072685e7d&safe=linea:0x9ff471F9f98F42E5151C7855fD1b5aa906b1AF7e)
- [x] [Mode](https://safe.optimism.io/transactions/queue?safe=mode:0x9ff471F9f98F42E5151C7855fD1b5aa906b1AF7e) - reject 0 exec 1
- [x] [Fraxtal](https://safe.optimism.io/transactions/tx?id=multisig_0x9ff471F9f98F42E5151C7855fD1b5aa906b1AF7e_0x47de4a3d1c2952e93e22026a15e5c3370435991288da7c3d67f847ccde42a4ce&safe=fraxtal:0x9ff471F9f98F42E5151C7855fD1b5aa906b1AF7e)

### CODE REVIEW

**Comment by Tritium-VLK** [comment]
Please review and execute all 3 transactions above before merging this pr.  Note that the safes will be added to bal_addresses once this PR has been merged/everything has been verified.

https://github.com/BalancerMaxis/bal_addresses/pull/291

These transactions remove shak as a signer and accept ownership of the gas station on all 3 chains.

**Review by gosuto-inzasheru — CHANGES_REQUESTED** [review]
support for these chains still needs to be added to the ci reporting. also chain ids are all the same? i would expect three different ones

**Comment by Tritium-VLK** [comment]
> support for these chains still needs to be added to the ci reporting. also chain ids are all the same? i would expect three different ones

Mind if we merge this now anyway... Once this is done, can merge bal addresses, the the github poker will start poking the gas stattion so deployers have gas.

Agree on the ticket, but would be nice to not block this.  Seem reasonable?

**Review by gosuto-inzasheru — APPROVED** [review]
yes this is exactly why i moved it to its own issue :)

**Pull request merged**
