### PR TITLE
Keep running even if can't interface with a contract.

### PR DESCRIPTION
**Pull request by Tritium-VLK**
Currently failing due to issues interfacing with the mode gas station.

Works in dev environment, need better errors and other chains should still work.

### CODE REVIEW

**Comment by Tritium-VLK** [comment]
Somehow the string is being packed into a list of letters:
https://github.com/BalancerMaxis/multisig-ops/actions/runs/9453540054/job/26039135329

**Comment by Tritium-VLK** [comment]
Still no dice @gosuto-inzasheru @jalbrekt85 I'm at a loss.  Any ideas?

https://github.com/BalancerMaxis/multisig-ops/actions/runs/9453974172

**Comment by gosuto-inzasheru** [comment]
@Tritium-VLK the gas station address is a single item, so needs to be appended (contrary to eg `to_poke += book.extras.maxiKeepers.gaugeRewardsInjectors.values()`, which is a list already)

see 99b9022

**Comment by gosuto-inzasheru** [comment]
https://github.com/BalancerMaxis/multisig-ops/actions/runs/9466021547/job/26076764930

**Review by gosuto-inzasheru — APPROVED** [review]

**Comment by Tritium-VLK** [comment]
Hmm. I was reading the docs and everywhere i looked it said that += should be equivlent to .append() for string/list.  Guess not.

Thanks :)

I updated/became the newest approver so you can approve/we can merge.  Your changes look good to me.

**Pull request merged**
