### PR TITLE
BIP-576: Enable aUSDC/USDC and aUSDT/USDT gauges [Arbitrum]

### PR DESCRIPTION
**Pull request by Xeonus**
- Enable aUSDC/USDC and aUSDT/USDT ECLP gauges [Arbitrum]
- Forum post: https://forum.balancer.fi/t/bip-576-enable-ausdc-usdc-and-ausdt-usdt-gauges-arbitrum/5660
- Rate provider review: https://github.com/balancer/code-review/pull/33
- core pools can't be added yet as contracts for LP tokens are not verified and no UI is present / mapped for them neither on Balancer nor Gyro. Can add later. Asked Gyro to provide info asap

### CODE REVIEW

**Review by gosuto-inzasheru — COMMENTED** [review]
pool contracts have still not been verified

other than that lgtm

**Comment by Tritium-VLK** [comment]
Will leave this unapproved/merged until the contracts are verified. If the BIP passes but the contracts are not verified, we can apply the PR next week once we can finish our review.

**Comment by Xeonus** [comment]
Contracts are verified now. Please recheck

**Review by gosuto-inzasheru — DISMISSED** [review]
confirmed

**Comment by Tritium-VLK** [comment]
Verified that rate providers matched.

**Review by Tritium-VLK — APPROVED** [review]

**Review by gosuto-inzasheru — APPROVED** [review]

**Pull request merged**
