### PR TITLE
Remove LZ Poker from Gas Station and remove funds

### PR DESCRIPTION
**Pull request by Hyferion**
**IMPORTANT: Execute "remove_lz_from_gassation.json" (MAXI_OPS) BEFORE "withdraw_lz_second.json" (LM)**

### CODE REVIEW

**Review by gosuto-inzasheru — CHANGES_REQUESTED** [review]
sim for the gas station is currently failing, since the owner is not the lm msig but the payments msig.

see tenderly url and `GasStationV2.owner()`

**Comment by Hyferion** [comment]
> sim for the gas station is currently failing, since the owner is not the lm msig but the payments msig.
> 
> see tenderly url and `GasStationV2.owner()`



> sim for the gas station is currently failing, since the owner is not the lm msig but the payments msig.
> 
> see tenderly url and `GasStationV2.owner()`

yes ofc. Resolved

**Review by gosuto-inzasheru — DISMISSED** [review]
- ops: remove poker from watchlist
- lm: retrieve its surplus of gas and send it back to the gas station

(in that order!)

**Review by Tritium-VLK — APPROVED** [review]

**Comment by Tritium-VLK** [comment]
maxiOPs: https://app.onchainden.com/safes/eth:0x166f54F44F271407f24AA1BE415a730035637325/transactions/0x3f6af616d5713d5cd79e389d51cba30ecf857957081a30255323b26a1944a0e6?nid=325416
LM: https://app.onchainden.com/safes/eth:0xc38c5f97B34E175FFd35407fc91a937300E33860/transactions/0x2997fae3d1c4aebf32b03eda455a20d012a3a1dbfe50a5c6debf3a6e8d385523?nid=325396

**Pull request merged**
