### PR TITLE
simulate actions of vote.py in review_votes.py

### PR DESCRIPTION
**Pull request by jalbrekt85**
#1517 - review_vote.py now simulates actions of vote.py, mainly parsing the vote csv and generating the EIP712 payload/message hash

### CODE REVIEW

**Review by gosuto-inzasheru — COMMENTED** [review]
lgtm, but maybe wait until there is a payload that we can run on this branch to test it properly?

**Comment by gosuto-inzasheru** [comment]
can you add `workflow_dispatch` to `.github/workflows/review_aura_gauge_votes.yaml`?

**Comment by jalbrekt85** [comment]
> can you add `workflow_dispatch` to `.github/workflows/review_aura_gauge_votes.yaml`?

good idea, added in ba1ba1ba1e

**Comment by jalbrekt85** [comment]
> ## vLAURA Votes Review
> CSV file: `MaxiOps/vlaura_voting/2024/W50/input/BD Vote Template - November 21 2024 (1) - BD Vote Template - November 21 2024 (1).csv`
...

temporarily added votes from last round to this branch to test ^^^

**Review by gosuto-inzasheru — APPROVED** [review]
great! test run in pr gives a lot more confidence. lfg!

**Comment by Xeonus** [comment]
Very nice indeed! Great work @jalbrekt85 !

**Pull request merged**
