### PR TITLE
BIP-544: Linear Pool Hack Restitution

### PR DESCRIPTION
**Pull request by gosuto-inzasheru**
there is an airdrop csv generator based on the results of the [claim form](https://app.balancer.fi/#/ethereum/claim-submission) here: https://docs.google.com/spreadsheets/d/1oAAqh2fJnR4EwnHYiKzuJoWZfy1GxmOPTkDj2SAR71I/edit#gid=1201725315

i added a preliminary csv that assumes 75% restitution at at $bal price of $3.65

the csv can be uploaded into the safe app here: https://app.safe.global/apps/open?safe=eth:0x10A19e7eE7d7F8a52822f6817de8ea18204F2e4f&appUrl=https%3A%2F%2Fcloudflare-ipfs.com%2Fipfs%2FQmTpg77NY45oyx2Qtsa8WXCDby3qeKrCCNjr4JUJekSsyR

for the two optimism victims, beets has agreed to pay half of the amount to be restituted. we therefore send the beets treasury: `5861.28 * .75 * .5 = 2197.98` usdc (note the `.75` is currently assumed). i opted for usdc here since the amount is very minimal and beets treasury already communicated that they will pay out in usdc.

### CODE REVIEW

**Comment by Tritium-VLK** [comment]
> there is an airdrop csv generator based on the results of the [claim form](https://app.balancer.fi/#/ethereum/claim-submission) here: https://docs.google.com/spreadsheets/d/1oAAqh2fJnR4EwnHYiKzuJoWZfy1GxmOPTkDj2SAR71I/edit#gid=1201725315
> 
> i added a preliminary csv that assumes 75% restitution at at $bal price of $3.65
> 
> the csv can be uploaded into the safe app here: https://app.safe.global/apps/open?safe=eth:0x10A19e7eE7d7F8a52822f6817de8ea18204F2e4f&appUrl=https%3A%2F%2Fcloudflare-ipfs.com%2Fipfs%2FQmTpg77NY45oyx2Qtsa8WXCDby3qeKrCCNjr4JUJekSsyR
> 
> for the two optimism victims, beets has agreed to pay half of the amount to be restituted. we therefore send the beets treasury: `5861.28 * .75 * .5 = 2197.98` usdc (note the `.75` is currently assumed). i opted for usdc here since the amount is very minimal and beets treasury already communicated that they will pay out in usdc.|

Beets has agreed/already done governance around accepting the 50% of reported Op losses in BAL.  Otherwise, this looks good.  Can regenerate payloads as close as possible to the time of payment as governance allows with up to date pricing.

**Comment by Tritium-VLK** [comment]
@gosuto-inzasheru I pushed a draft MD file for the BIP.  Mind filling it out and helping me get it all to link together.

I think if we take the airdrop CSV and add beets into it as well so the entire amount is there.  From that most of the amounts should be easier to exactly determine in both USD and BAL values for the text.

Further Any ideas of an easy way to get receiver, amount, usd_value loaded into an MD table so people notice it is there.  We want people to look at it and I don't think enough have.

Thanks

**Comment by Tritium-VLK** [comment]
Let's wait to merge this until we have a final payload on Monday.

**Comment by Tritium-VLK** [comment]
@gosuto-inzasheru I no longer see the op payments to beets in the sheet.  Further there has been a request from Beethoven X to update that address.  As owner/editor of the sheet, do you mind adding the beets payment back in to the sheet.

We can coordinate on Monday to do a final review and generate a new CSV if required based on BAL price. 

https://forum.balancer.fi/t/bip-xxx-linear-pool-hack-restituion/5541/3?u=tritium

**Comment by gosuto-inzasheru** [comment]
i had already changed the address in the csv in 71974b5, and in the address book in https://github.com/BalancerMaxis/bal_addresses/pull/185

now also amended the csv generator

**Review by Tritium-VLK — APPROVED** [review]

**Comment by Tritium-VLK** [comment]
Payment TXs:
https://etherscan.io/tx/0x4ae7fc60543e7b9c7972428662d9fc579f08384f76af9dea31e6b5cfe8d3d021
https://optimistic.etherscan.io/tx/0x3faf464a10c766c684ce23477c6c1fe7974a4c99e0e2a7a951af9180ad6556fc

**Pull request merged**
