### PR TITLE
BIP-551: Claim and Relock Balancer DAO’s AURA / vlAURA

### PR DESCRIPTION
**Pull request by Xeonus**
- Relock expired lock AFTER March 7th and BEFORE March 14th
- Claim and lock vest AFTER March 7th and BEFORE March 14th -> sim fails until March 7th as no lock has expired until then

### CODE REVIEW

**Comment by gosuto-inzasheru** [comment]
i pushed a fix for the report script straight to this branch, hope you dont mind

**Review by gosuto-inzasheru — COMMENTED** [review]
tbh i would suggest to leave this pr open until march 7th, and confirm a proper sim. or at least double check the sim once made part of a combined payload pr!!!

even though the status shows up as successful, it currently reverts on: `require(locked > 0, "no exp locks");`

**Comment by Xeonus** [comment]
@Tritium-VLK we need to decide when to merge this DAO multi-sig payload as it has a timing requirement (execution after March 7th and before March 14th).

**Comment by Tritium-VLK** [comment]
> @Tritium-VLK we need to decide when to merge this DAO multi-sig payload as it has a timing requirement (execution after March 7th and before March 14th).

This will be loaded on Monday when voting ends, then I'll make sure the multisig knows it needs to be executed by thursday and nudge hard if it's not happening.

**Comment by Tritium-VLK** [comment]
> tbh i would suggest to leave this pr open until march 7th, and confirm a proper sim. or at least double check the sim once made part of a combined payload pr!!!
> 
> even though the status shows up as successful, it currently reverts on: `require(locked > 0, "no exp locks");`

Agreed.   

@gosuto-inzasheru Also there is  a merge conflict on the changes to script_utils that I don't understand.  Can you either remove it, or abstract these changes to a separate PR which we can review/merge/rebase this guy off the fresh main.

either approach is fine, but I'm a bit unclear on where the merge conflict came from/how to handle it

**Comment by gosuto-inzasheru** [comment]
fixed. was just an indentation/linting issue

**Review by gosuto-inzasheru — APPROVED** [review]
sim looking good now after 7 march

**Pull request merged**
