### PR TITLE
Create T_PaladinQuestBoard.json

### PR DESCRIPTION
**Pull request by Zen-Maxi**
image

### CODE REVIEW

**Review by gosuto-inzasheru — APPROVED** [review]
decodes to `add_reward(threshold_t_token, QuestBoardV2_1)`

**Comment by gosuto-inzasheru** [comment]
the other two gauges `0xBC02eF87f4E15EF78A571f3B2aDcC726Fee70d8b` (gauges/DOLA-USDC BSP-gauge-bc02) and `0xCD19892916929F013930ed628547Cc1F439b230e` (gauges/sDOLA-DOLA BSP-gauge-cd19) indeed already have $inv as a reward token

**Comment by Tritium-VLK** [comment]
@Zen-Maxi has this already been executed?  If so can you merge it?

**Comment by gosuto-inzasheru** [comment]
https://etherscan.io/tx/0x7315e48fbf5be50cd60538cbd3a377a698575d80c531230689cf377455d70feb

**Pull request merged**
