### PR TITLE
Upgrade to Brownie 1.20.4 running from our local repo with extentions + use python 3.10 for poker

### PR DESCRIPTION
**Pull request by Tritium-VLK**
brownie version 1.20.3 vanished, jobs started failing.  Switch back to our own repo, and manage from there.

Note that I updated v1.20.x branch to 1.20.4 + our new chains and am using that version for this test.

https://github.com/BalancerMaxis/brownie/commit/e29caeaa7b8f8b6a909f7c464d6d5d9f633a2988

### CODE REVIEW

**Comment by Tritium-VLK** [comment]
Successful poke run - was failing on main: https://github.com/BalancerMaxis/multisig-ops/actions/runs/9008330571

**Comment by Tritium-VLK** [comment]
https://github.com/BalancerMaxis/multisig-ops/actions/runs/9008418150

**Comment by gosuto-inzasheru** [comment]
wdym vanished?

**Comment by Tritium-VLK** [comment]
> wdym vanished?

I thought they had deleted the tag/release, but the situatuion was more the case that some jobs were running python3.9 and these packages do not work for/exist for python3.9.

**Review by gosuto-inzasheru — APPROVED** [review]
always good to stay up to date with package releases

we need the custom branch for unsupported chains

**Pull request merged**
