### PR TITLE
Payload for PUR#5 (Mainnet)

### PR DESCRIPTION
**Pull request by JeronimoHoulin**

### CODE REVIEW

**Comment by gosuto-inzasheru** [comment]
https://forum.balancer.fi/t/bip-xxx-permissions-policy-update-request-5/6129

**Comment by gosuto-inzasheru** [comment]
review here: https://forum.balancer.fi/t/bip-733-permissions-policy-update-request-5-eth-mainnet/6129/2?u=gosuto

**Comment by Zen-Maxi** [comment]
Please adjust this to no longer be BIP-733 as it will not go in W48 due to outstanding comments

**Comment by gosuto-inzasheru** [comment]
it wasnt numbered here yet, only in the forum. that has been changed already so all good.

**Comment by gosuto-inzasheru** [comment]
note to self: also move pur6 into the same week dir as where this one will end up

**Comment by gosuto-inzasheru** [comment]
superseded by #1581

**Pull request closed without merging**
