### PR TITLE
BIP-575: Enable stataArbUSDT/stataArbUSDCn gauge [Arbitrum]

### PR DESCRIPTION
**Pull request by Xeonus**
- enable E-CLP gauge for stataArbUSDT/stataArbUSDCn gauge on Arbitrum
- rate providers are implemented with the ERC4626 standard
- rate provider review: https://github.com/balancer/code-review/pull/33
- Forum post: https://forum.balancer.fi/t/bip-575-enable-stataarbusdt-stataarbusdcn-gauge-arbitrum/5643

### CODE REVIEW

**Comment by Xeonus** [comment]
Waiting on confirmation from @Zen-Maxi that these pools are good to go. Assuming core pool status but also waiting on confirmation for that

**Review by gosuto-inzasheru — APPROVED** [review]

**Review by Tritium-VLK — DISMISSED** [review]

**Comment by Tritium-VLK** [comment]
@gosuto-inzasheru does this pool have rate providers (it's core so it should, but the report is not showing them - old one was).  Did you check them?

**Comment by gosuto-inzasheru** [comment]
> @gosuto-inzasheru does this pool have rate providers (it's core so it should, but the report is not showing them - old one was). Did you check them?

@Tritium-VLK yes i checked them. rate provider is not showing in ci report, same as my comment for pr852: https://github.com/BalancerMaxis/multisig-ops/pull/852#pullrequestreview-1965938106

**Comment by Tritium-VLK** [comment]
At best merge #878 before this PR.

**Review by gosuto-inzasheru — DISMISSED** [review]

**Review by Tritium-VLK — APPROVED** [review]

**Pull request merged**
